### ISSUE TITLE
Fixed in Magento 1.9.3.1

### ISSUE THREAD

**Issue by sprankhub** [AmpersandHQ/magento-ce-ee-config-corruption-bug#9]
Thanks for all your work!

You may want to add that this issue is fixed in Magento 1.9.3.1. See https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Core/Model/Config.php#L260

**Comment by convenient** [comment]
Amazing news, thank you @sprankhub!

 I'll make sure to update the main `README.md` soon, it's great to know that Magento has _finally_ added this work to the core. 

Now, If only they provided accreditation like they do for security patches. I mean, a website being down is no big deal right ¯\\_(ツ)_/¯

**Comment by sprankhub** [comment]
What is that accreditation!? ¯\\_(ツ)_/¯

**Comment by convenient** [comment]
You get $$$ for security patches and listed as "Reporter" on the [patch breakdown](https://magento.com/security/patches/supee-6788). Kudos basically.

I know Magento read this article because I could see them in the referrers, but it would be nice for them to acknowledge that they took this work from here and included it in the core. 

Oh well, I must try not to be bitter!

**Comment by convenient** [comment]
Thanks for the info, I've updated the main `readme.md`.

https://github.com/AmpersandHQ/magento-ce-ee-config-corruption-bug#update-3-baked-into-the-core

**Comment by sajidunnar** [comment]
@convenient Luke Thanks for such awesome fix, we are having a similar issue, sometimes our cart page  body comes as white/ black but with correct footer and header.

I applied your patches but I think you may share some insight or give more idea to debug this further ?


Can you share your last Config.php with the changes you mentioned in Improvement section.
